---
# Main tasks for setting up attack boxes
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install basic tools
  apt:
    name:
      # Basic networking tools
      - net-tools
      - tcpdump
      - nmap
      - curl
      - wget
      # Useful utilities
      - git
      - vim
      - htop
      - unzip
      - python3
      - python3-pip
      - openssh-server
      - dnsutils
      - iputils-ping
      - traceroute
      - ubuntu-desktop
    state: present

- name: Install additional security tools
  apt:
    name: "{{ attackbox_additional_tools }}"
    state: present
  failed_when: false

- name: Install Python tools for pentesting
  pip:
    name: "{{ attackbox_additional_python_tools }}"
    state: present
  failed_when: false

- name: Configure hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'

- name: Enable and start SSH
  service:
    name: ssh
    state: started
    enabled: yes

- name: Configure firewall (UFW)
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - 22
    - 80
    - 443
    - 4444
    - 8080
  failed_when: false

- name: Enable UFW
  ufw:
    state: enabled
    policy: allow
  failed_when: false

- name: Create a test file to verify deployment
  file:
    path: /root/attackbox_deployed.txt
    state: touch
    mode: '0644'
    owner: root
    group: root
  
- name: Create attack tools directory
  file:
    path: /opt/attack-tools
    state: directory
    mode: '0755'

- name: Clone Git repositories
  git:
    repo: "{{ item.url }}"
    dest: "/opt/attack-tools/{{ item.name }}"
  loop: "{{ attackbox_git_repos }}"
  failed_when: false

- name: Set shell prompt and aliases
  blockinfile:
    path: /etc/profile.d/goad.sh
    create: yes
    block: |
      # GOAD environment settings
      export PS1="\[\033[1;31m\]\u@\h\[\033[1;34m\] \w\[\033[0m\]\$ "
      alias ll='ls -la'
      alias update='apt update && apt upgrade -y'
      alias nmap-quick='nmap -sV -sC -T4'
      alias nmap-full='nmap -sV -sC -p- -T4'
    mode: '0644'

- name: Create README file
  copy:
    dest: /opt/attack-tools/README.txt
    content: |
      This attack box is part of the GOAD (Game of Active Directory) environment.
      It is running Ubuntu 24.04 and is configured for offensive security testing.
      
      Useful commands:
      - nmap-quick [target IP] - Quick scan with service detection
      - nmap-full [target IP] - Full port scan with service detection
      - sudo responder -I eth0 -wrf - Start Responder
      - crackmapexec smb [IP/range] - Scan SMB services
      
      For more information about GOAD, visit: https://github.com/Orange-Cyberdefense/GOAD
    owner: root
    group: root
    mode: '0644'